const HatsActionTypes = {
    FETCH_ALL_HATS: "FETCH_ALL_HATS",
    FETCH_ALL_HATS_SUCCESS: "FETCH_ALL_HATS_SUCCESS",
    FETCH_ALL_HATS_FAILURE: "FETCH_ALL_HATS_FAILURE"
}

export default HatsActionTypes;