const JacketActionTypes = {
    FETCH_ALL_JACKETS: 'FETCH_ALL_JACKETS',
    FETCH_ALL_JACKETS_SUCCESS: 'FETCH_ALL_JACKETS_SUCCESS',
    FETCH_ALL_JACKETS_FAILURE: 'FETCH_ALL_JACKETS_FAILURE'
}

export default JacketActionTypes;